spring.application.name=shopsphere

spring.datasource.url=jdbc:postgresql://localhost:5432/shopsphere_db
spring.datasource.username=postgres
spring.datasource.password=student123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=9a67471ec6391621d4be883f0d03d3c87e8b3e8c56fa91176b6d5b0a3c20df89
jwt.expiration=86400000